package com.eq.doc.dto.user;

import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.enums.RelationTypeEnum;
import com.eq.doc.domain.User;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link User }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class UserWithPost3Response {


    private String id;
    private String name;
    /**
     * 用户发布的帖子集合
     **/
    @Navigate(value = RelationTypeEnum.OneToMany, limit = 3)
    private List<InternalPosts> posts;


    /**
     * {@link com.eq.doc.domain.Post }
     */
    @Data
    public static class InternalPosts {

        private String id;
        private String title;
        private LocalDateTime publishAt;
        /**
         * 评论信息
         **/
        @Navigate(value = RelationTypeEnum.OneToMany, limit = 3)
        private List<InternalComment> commentList;


    }

    /**
     * {@link com.eq.doc.domain.Comment }
     */
    @Data
    public static class InternalComment {
        private String id;
        private String content;
        private LocalDateTime createAt;

        @NavigateFlat(pathAlias = "user.id")
        private String userId;

        @NavigateFlat(pathAlias = "user.name")
        private String userName;

    }

}
