package com.eq.doc.dto.comment;

import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.annotation.NavigateFlat;
import com.easy.query.core.enums.RelationTypeEnum;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.eq.doc.domain.Comment }
 * @easy-query-dto schema: normal
 *
 * @author xuejiaming
 */
@Data
public class MyCommentDTO {


    private String id;
    private String parentId;//因为在内存中聚合所以parentId必须要有
    private String content;
    @NavigateFlat(pathAlias = "user.name")
    private String userName;
    private LocalDateTime createAt;
    /**
     * 子评论
     **/
    @Navigate(value = RelationTypeEnum.OneToMany,selfProperty = "id",targetProperty = "parentId",supportNonEntity = true)
    private List<MyCommentDTO> children;

}
